version: '3.8'

services:
    migrations:
      build: ./backend
      env_file:
        - ./backend/.env
      environment:
        - POSTGRES_HOST=db
      depends_on:
        db:
          condition: service_healthy
      command: python manage.py migrate

    db:
      image: postgres:15.2
      ports:
        - "5432:5432"
      env_file:
        - ./backend/.env
      restart: always
      volumes:
        - pg_data:/var/lib/postgresql/data/
      healthcheck:
        test: pg_isready -U admin -d telemessage_bridge
        interval: 3s
        retries: 10
        timeout: 3s
volumes:
  pg_data: