# Generated by Django 4.2.4 on 2023-08-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bot_url',
            field=models.CharField(default='t.me/telemessage_bridge_bot', max_length=100, verbose_name='Ссылка на бота'),
        ),
    ]
