# Generated by Django 4.2.4 on 2023-08-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bot_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bot_url',
        ),
    ]
